--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.304.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/23/2020 9:07:11 AM
-- Server version: 8.0.20
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE toco_webapp;

--
-- Drop procedure `getAllCollection`
--
DROP PROCEDURE IF EXISTS getAllCollection;

--
-- Drop table `product_category`
--
DROP TABLE IF EXISTS product_category;

--
-- Drop table `product`
--
DROP TABLE IF EXISTS product;

--
-- Drop table `product_product_category`
--
DROP TABLE IF EXISTS product_product_category;

--
-- Set default database
--
USE toco_webapp;

--
-- Create table `product_product_category`
--
CREATE TABLE product_product_category (
  id int NOT NULL AUTO_INCREMENT,
  product_id int NOT NULL,
  product_category_id int NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `product`
--
CREATE TABLE product (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(256) NOT NULL,
  description varchar(2000) DEFAULT NULL COMMENT 'Mô tả sản phẩm',
  origin_price int UNSIGNED ZEROFILL NOT NULL COMMENT 'Giá gốc',
  sale_price int UNSIGNED ZEROFILL NOT NULL COMMENT 'Giá khuyến mãi',
  image_path varchar(2000) DEFAULT NULL COMMENT 'Đường dẫn ảnh',
  is_new tinyint NOT NULL DEFAULT 1 COMMENT 'is sản phẩm mới',
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Sản phẩm bán tại Toco';

--
-- Create table `product_category`
--
CREATE TABLE product_category (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(256) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `getAllCollection`
--
CREATE DEFINER = 'bhtrang'@'localhost'
PROCEDURE getAllCollection ()
BEGIN
  DECLARE finished integer DEFAULT 0;
  DECLARE categoryId int DEFAULT 0;

  DECLARE cursorCategory CURSOR FOR
  SELECT
    id
  FROM product_category pc;

  DECLARE CONTINUE HANDLER
  FOR NOT FOUND SET finished = 1;

  CREATE TEMPORARY TABLE product_temp
  SELECT
    *,
    0 categoryId
  FROM product p
  LIMIT 0;

  OPEN cursorCategory;

getCategory:
  LOOP
    FETCH cursorCategory INTO categoryId;
    IF finished = 1 THEN
      LEAVE getCategory;
    END IF;

    INSERT INTO product_temp
      SELECT
        p.*,
        ppc.product_category_id AS categoryId
      FROM product p
        INNER JOIN product_product_category ppc
          ON p.id = ppc.product_id
      WHERE ppc.product_category_id = categoryId LIMIT 6;
  END LOOP getCategory;
  CLOSE cursorCategory;

  SELECT
    *
  FROM product_temp pt;
  DROP TABLE product_temp;
END
$$

DELIMITER ;

-- 
-- Dumping data for table product_product_category
--
INSERT INTO product_product_category VALUES
(1, 1, 1),
(2, 2, 1),
(3, 3, 1),
(4, 4, 1),
(5, 5, 1),
(6, 6, 1),
(7, 7, 1);

-- 
-- Dumping data for table product_category
--
INSERT INTO product_category VALUES
(1, 'MÓN NỔI BẬT'),
(2, 'TRÀ SỮA'),
(3, 'CHÈ'),
(4, 'FRESH FRUIT TEA'),
(5, 'MACCHIATO'),
(6, 'SPECIAL DRINK');

-- 
-- Dumping data for table product
--
INSERT INTO product VALUES
(1, 'CREAM - CATCHER CAFÉ (M)', 'Creamcake béo ngậy độc quyền của ToCoToCo hòa quyện cùng Cà phê Đaklak thơm nồng', 0000050000, 0000030000, '_ut443lyh0.jpg', 1),
(2, 'ENERGY - BOOSTER CAFÉ (M)', 'Cà phê Đaklak thơm nồng kết hợp cùng thạch Café giòn dai', 0000045000, 0000025000, '_ea9m7xzs0.jpg', 1),
(3, 'HỒNG LONG BẠCH NGỌC (M)', 'Sữa chua lên men tự nhiên quyện cùng mứt thanh long đỏ Bình Thuận thơm mát', 0000045000, 0000025000, '_bmiapz4sg.jpg', 1),
(4, 'HỒNG LONG PHA LÊ TUYẾT (M)', 'Trà xanh Organic vị nhài hòa cùng mứt thanh long đỏ Bình Thuận và thạch băng tuyết dai dai', 0000038000, 0000025000, '_zt6t3eezv.jpg', 1),
(5, 'OOLONG TRÂN CHÂU BABY KEM CAFÉ (M)', 'Ô long Organic Mộc Châu kết hợp cùng trân châu baby độc quyền hòa quyện với lớp kem café sánh mịn', 0000046000, 0000025000, '_nmff6nu0r.jpg', 1),
(6, 'SỮA TƯƠI TRÂN CHÂU BABY KEM CAFÉ (M)', 'Sữa tươi nguyên chất kết hợp cùng trân châu baby độc quyền hòa quyện với lớp kem café sánh mịn', 0000048000, 0000025000, NULL, 1),
(7, 'TIGER SUGAR', 'Tiger Sugar là sự kết hợp hoàn hảo giữa vị ngọt đặc trưng của siro đường hổ quyện với vị ngậy béo của sữa tươi cùng trân châu dẻo dai uống rồi lại muốn thêm ly nữa.', 0000050000, 0000025000, NULL, 1);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;